chore: better branding?

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -1,4 +1,4 @@
-name: Prettier
+name: 🤖 Auto Prettier ✨
 
 on: push
 
@@ -8,6 +8,7 @@ concurrency:
 
 jobs:
   run:
+    name: Prettier if needed
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -16,11 +17,11 @@ jobs:
           cache: npm
           node-version: lts/*
       - run: npm ci --no-scripts
-      - run: npx prettier --ignore-path .gitignore --check ".github/workflows/**/*.yml"
-      - if: ${{ failure() }}
-        run: echo "An action can't make changes to actions, you'll have to run prettier manually"
+      - name: check if workflows needs prettier
+        run: npx prettier --ignore-path .gitignore --check ".github/workflows/**/*.yml" || echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1
       - run: npx prettier --ignore-path .gitignore --write .
       - uses: EndBug/add-and-commit@v9
         with:
           commit: --no-verify
           message: 'chore(bot): prettier formatting [skip release]'
+          default_author: github_actions
