chore: use lsit construct

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -18,7 +18,7 @@ jobs:
           node-version: lts/*
       - run: npm ci --no-scripts
       - name: check if workflows needs prettier
-        run: npx prettier --ignore-path .gitignore --check ".github/workflows/**/*.yml" || echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1
+        run: npx prettier --ignore-path .gitignore --check ".github/workflows/**/*.yml" || (echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1)
       - run: npx prettier --ignore-path .gitignore --write .
       - uses: EndBug/add-and-commit@v9
         with:
